# Save the plot generated by the reader's simulation code.
dosing_plot = include(joinpath(@__DIR__, "run.jl"))

# Check that all eight doses, including both stop times, were applied.
result = sim(Scenario(model, (0., 600.)))
expected = sum(10 * exp(-1e-2 * (600 - t)) for t in 144:24:216) +
    sum(20 * exp(-1e-2 * (600 - t)) for t in 384:24:456)
@assert isapprox(last(result[:drug, :]), expected; rtol = 3e-3)
println("Final concentration agrees with the analytical dosing solution")

plot!(dosing_plot;
    size = (750, 380), margin = 5 * Plots.mm,
    title = "Two dosing series", titlefontsize = 12,
    xlabel = "Time", ylabel = "Drug concentration", label = "drug"
)

output_dir = joinpath(@__DIR__, "..", "img")
mkpath(output_dir)
savefig(dosing_plot, joinpath(output_dir, "repeated-dosing.png"))
println("Saved repeated-dosing.png")
